if (!("readxl") %in% installed.packages()) install.packages("readxl")
if (!("ggplot2") %in% installed.packages()) install.packages("ggplot2")
library(ggplot2)
library(readxl)
covid_19_bauru_mortes <- read_excel("./dados/covid_19_bauru_mortes.xlsx", range=cell_cols("G:G"), col_types=c("date"))
obitos <- table(covid_19_bauru_mortes)
barplot(obitos[-1])
mtext(side = 1, text = "Data", line = 2)
mtext(side = 2, text = "Óbitos", line = 2)